# Package for defining labelled graph representations.

py_library(
    name = "database_exporters",
    srcs = ["database_exporters.py"],
    visibility = ["//deeplearning/ml4pl:__subpackages__"],
    deps = [
        "//deeplearning/ml4pl/bytecode:bytecode_database",
        "//deeplearning/ml4pl/graphs:graph_database",
        "//labm8:app",
        "//labm8:humanize",
        "//labm8:labtypes",
        "//labm8:sqlutil",
    ]
)
