# Automatically-generated documentation for command-line tools.
#
# Copyright 2019-2020 the ProGraML authors.
#
# Contact Chris Cummins <chrisc.101@gmail.com>.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

genrule(
    name = "analyze",
    outs = ["analyze.txt"],
    cmd = "$(location //programl/cmd:analyze) --helpfull > $@ || true",
    tools = ["//programl/cmd:analyze"],
)

genrule(
    name = "clang2graph",
    outs = ["clang2graph.txt"],
    cmd = "$(location //programl/cmd:clang2graph) -help > $@ || true",
    tools = ["//programl/cmd:clang2graph"],
)

genrule(
    name = "graph2cdfg",
    outs = ["graph2cdfg.txt"],
    cmd = "$(location //programl/cmd:graph2cdfg) --helpfull > $@ || true",
    tools = ["//programl/cmd:graph2cdfg"],
)

genrule(
    name = "graph2dot",
    outs = ["graph2dot.txt"],
    cmd = "$(location //programl/cmd:graph2dot) --helpfull > $@ || true",
    tools = ["//programl/cmd:graph2dot"],
)

genrule(
    name = "graph2json",
    outs = ["graph2json.txt"],
    cmd = "$(location //programl/cmd:graph2json) --helpfull > $@ || true",
    tools = ["//programl/cmd:graph2json"],
)

genrule(
    name = "graph2nx",
    outs = ["graph2nx.txt"],
    cmd = "$(location //programl/cmd:graph2nx) --helpfull > $@ || true",
    tools = ["//programl/cmd:graph2nx"],
)

genrule(
    name = "graph2seq",
    outs = ["graph2seq.txt"],
    cmd = "$(location //programl/cmd:graph2seq) --helpfull > $@ || true",
    tools = ["//programl/cmd:graph2seq"],
)

genrule(
    name = "inst2vec",
    outs = ["inst2vec.txt"],
    cmd = "$(location //programl/cmd:inst2vec) --helpfull > $@ || true",
    tools = ["//programl/cmd:inst2vec"],
)

genrule(
    name = "llvm2graph",
    outs = ["llvm2graph.txt"],
    cmd = "$(location //programl/cmd:llvm2graph) --helpfull > $@ || true",
    tools = ["//programl/cmd:llvm2graph"],
)

genrule(
    name = "pbq",
    outs = ["pbq.txt"],
    cmd = "$(location //programl/cmd:pbq) --helpfull > $@ || true",
    tools = ["//programl/cmd:pbq"],
)

genrule(
    name = "xla2graph",
    outs = ["xla2graph.txt"],
    cmd = "$(location //programl/cmd:xla2graph) --helpfull > $@ || true",
    tools = ["//programl/cmd:xla2graph"],
)
