---
name: Install build dependencies
runs:
    using: composite
    steps:
        - name: Install dependencies (linux)
          run: |
              if [ "$(uname)" != "Darwin" ]; then
                  curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64" > bazel
                  chmod +x bazel
                  sudo mv bazel /usr/local/bin/bazel
                  sudo apt-get install clang-9 patchelf
              fi
          shell: bash

        - name: Install dependencies (macos)
          run: |
              if [ "$(uname)" = "Darwin" ]; then
                  brew install bazelisk zlib
              fi
          shell: bash
          env:
              LDFLAGS: -L/usr/local/opt/zlib/lib
              CPPFLAGS: -I/usr/local/opt/zlib/include
              PKG_CONFIG_PATH: /usr/local/opt/zlib/lib/pkgconfig

        - name: Install Python dependencies
          run: |
              python -m pip install -r requirements.txt
              echo /home/runner/.local/bin >> $GITHUB_PATH
          shell: bash

        - name: Create DGL directory
          run: |
              mkdir ~/.dgl
              touch ~/.dgl/config.json
          shell: bash

        - name: whoami
          run: ./tools/whoami.sh
          shell: bash
