# This package defines a Dockerfile image capable of running this project.

# Since the installation is described using a Dockerfile, bazel cannot build
# it.
filegroup(
  name = "phd",
  srcs = ["Dockerfile"]
)
