---
name: CI

on:
    push:
        branches:
            - development
            - stable
    pull_request:

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python: [3.9]
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install build dependencies
              uses: ./.github/actions/install-build-dependencies

            - name: Install
              run: |
                  mkdir "${GITHUB_WORKSPACE}/install"
                  bazel run --config=ci //:install "${GITHUB_WORKSPACE}/install"
                  echo "${GITHUB_WORKSPACE}/install/bin" >> $GITHUB_PATH
                  echo "LD_LIBRARY_PATH=${GITHUB_WORKSPACE}/install/lib" >> $GITHUB_ENV

            - name: Test installed binaries
              run: |
                  llvm2graph --version
