---
name: Test Coverage

on:
    push:
        branches:
            - development
            - stable
    pull_request:

jobs:
    pytest-cov:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install build dependencies
              uses: ./.github/actions/install-build-dependencies

            - name: Install
              run: make install
              env:
                  BAZEL_OPTS: --batch
                  BAZEL_BUILD_OPTS: --config=ci

            - name: Test
              # Note the `|| true` as we don't care about failing tests in this
              # job.
              run: make install-test-cov || true

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  files: ./coverage.xml
              if: ${{ always() }}
